spring:
  application:
    name: UserService

  datasource:
    .url: jdbc:mysql://localhost:3306/user-service
    .username: root
    .password: password

  jpa:
    .hibernate:
      ddl-auto: update
    .show-sql: true

server:
  port: 8080

